
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASIGNACION DIVISION IDENTIFICADOR LLAVE_DERECHA LLAVE_IZQUIERDA MENOR_MENOR MULTIPLICACION NUMERO OPERADOR_ASIGNACION OPERADOR_SUMA PALABRA_RESERVADA PARENTESIS_DERECHO PARENTESIS_IZQUIERDO PUNTO_COMA RESTA STRING SUMAprogram : statementsstatements : statement statementsstatements : statement : declaration\n                 | assignment\n                 | printdeclaration : PALABRA_RESERVADA IDENTIFICADOR PUNTO_COMAassignment : IDENTIFICADOR ASIGNACION expression PUNTO_COMAexpression : IDENTIFICADORprint : PALABRA_RESERVADA MENOR_MENOR expression PUNTO_COMAexpression : NUMERO'
    
_lr_action_items = {'$end':([0,1,2,3,4,5,6,9,13,18,19,],[-3,0,-1,-3,-4,-5,-6,-2,-7,-10,-8,]),'PALABRA_RESERVADA':([0,3,4,5,6,13,18,19,],[7,7,-4,-5,-6,-7,-10,-8,]),'IDENTIFICADOR':([0,3,4,5,6,7,11,12,13,18,19,],[8,8,-4,-5,-6,10,15,15,-7,-10,-8,]),'MENOR_MENOR':([7,],[11,]),'ASIGNACION':([8,],[12,]),'PUNTO_COMA':([10,14,15,16,17,],[13,18,-9,-11,19,]),'NUMERO':([11,12,],[16,16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statements':([0,3,],[2,9,]),'statement':([0,3,],[3,3,]),'declaration':([0,3,],[4,4,]),'assignment':([0,3,],[5,5,]),'print':([0,3,],[6,6,]),'expression':([11,12,],[14,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statements','program',1,'p_program','parser.py',5),
  ('statements -> statement statements','statements',2,'p_statements','parser.py',9),
  ('statements -> <empty>','statements',0,'p_statements_empty','parser.py',13),
  ('statement -> declaration','statement',1,'p_statement','parser.py',17),
  ('statement -> assignment','statement',1,'p_statement','parser.py',18),
  ('statement -> print','statement',1,'p_statement','parser.py',19),
  ('declaration -> PALABRA_RESERVADA IDENTIFICADOR PUNTO_COMA','declaration',3,'p_declaration','parser.py',23),
  ('assignment -> IDENTIFICADOR ASIGNACION expression PUNTO_COMA','assignment',4,'p_assignment','parser.py',27),
  ('expression -> IDENTIFICADOR','expression',1,'p_expression','parser.py',31),
  ('print -> PALABRA_RESERVADA MENOR_MENOR expression PUNTO_COMA','print',4,'p_print','parser.py',35),
  ('expression -> NUMERO','expression',1,'p_expression_number','parser.py',39),
]
